### ISSUE TITLE
Does Litepub provide paging of blog posts?

### ISSUE THREAD

**Issue by phayz** [mirovarga/litepub#13]
I created about 10 example posts, to see if Litepub would begin breaking the posts into pages. I have not yet seen a page indicator appear. If I continue using Litepub, my concern is that someone wanting to view my posts views *all* of them, which seems like a waste of network traffic. Is there a way of breaking the posts into, perhaps, 5 per "page" or similar grouping?

**Comment by tyeeman** [comment]
He says here, last post - https://github.com/mirovarga/litepub/issues/2
Not likely.

**Comment by phayz** [comment]
Closed as this question is answered in issue #2 (as mentioned by @tyeeman). https://github.com/mirovarga/litepub/issues/2#issuecomment-238178030
