### ISSUE TITLE
Are the dates supposed to be visible?

### ISSUE THREAD

**Issue by tyeeman** [mirovarga/litepub#15]
Was just updating some pages and I noticed no dates are appearing in the index or on any blog page? Titles and Tags are showing. Has it been this way since day 1 or am I missing something that was never there?

**Comment by mirovarga** [comment]
Just have a look at [my blog](http://mirovarga.com) - it uses the default template and dates are visible both on the index and post pages,

**Comment by kfbeth** [comment]
I changed the template and must have missed the dates somewhere.

**Comment by tyeeman** [comment]
I'm trying to find the code that generates the date. Is this it - 
```
{{range $e.Tags}}
                  <a href="/tags/{{. | slug}}.html" title="Posts Tagged {{.}}">{{.}}</a>&nbsp;
                {{end}}
```

**Comment by mirovarga** [comment]
I'll try it and let you know.

**Comment by mirovarga** [comment]
I'm sorry I was wrong - my blog does **not** use the default template (which doesn't show dates as you observed).

Please have a look at my blog's [index](https://github.com/mirovarga/mirovarga.com/blob/master/templates/index.tmpl#L14) and [post](https://github.com/mirovarga/mirovarga.com/blob/master/templates/post.tmpl#L11) templates to see how I include the dates on the pages.
