### ISSUE TITLE
How can I hide one blog post from showing in the index

### ISSUE THREAD

**Issue by tyeeman** [mirovarga/litepub#16]
I'm building a site for a friend and they like Litepub very much. I am using one post as a landing page via redirects and it works good, however when the index.html is accessed all posts are shown including that post I'm using as a main page. Is there a way to not show that specific post on the index.html file? 

I remember you made an update to prevent a post from showing by adding a dot at the beginning of the file name, but then I can't access that file by a direct link can I?

**Comment by mirovarga** [comment]
If a post file starts with a dot or is in the `drafts` directory it is ignored (it means it won't be generated at all). Maybe try to use some condition in your template to ignore that specific post.
