### ISSUE TITLE
can u provide 32-bit version?

### ISSUE THREAD

**Issue by luckypoem** [mirovarga/litepub#2]
hi。
i see https://github.com/mirovarga/litepub/releases，there is no 32-bit version.can u provide 32-bit version?

and 
root@AR:/usr/local/go/gospace# /usr/local/go/bin/go get github.com/mirovarga/litepub
can't load package: package github.com/mirovarga/litepub: no buildable Go source files in /usr/local/go/gospace/src/github.com/mirovarga/litepub
root@AR:/usr/local/go/gospace# 

cannot  use "/usr/local/go/bin/go get github.com/mirovarga/litepub" to install litepub??
thank u!

**Comment by mirovarga** [comment]
You can build a 32-bit version yourself: set the `ARCH` variable in the `build.sh` script to `386` and run the script. The binary files will be in the `./bin` directory.

**Comment by luckypoem** [comment]
hi.
i ran the build.sh script but encountered many errors.i wonder why "/usr/local/go/bin/go get github.com/mirovarga/litepub" failed to install litepub??

or could u pls upload 32-bit version binary file?

**Comment by mirovarga** [comment]
I've added 32-bit versions to the latest release.

**Comment by luckypoem** [comment]
HI.

FINALLY, I SETUP THE BLOG SUCCESSFULLY: http://lp.smt.biz.st ,
but there are 2 questions:

1. the published posts seem randomly aligned.i publish this post http://lp.smt.biz.st/ce-shi-4.html after http://lp.smt.biz.st/ce-shi-3.html . the post http://lp.smt.biz.st/ce-shi-4.html  should be aligned in front of http://lp.smt.biz.st/ce-shi-3.html ,but actually not.
how to make posts aligned as per order of publishing time?

2. this blog app doesn't support pagination?how to paginate?

**Comment by mirovarga** [comment]
1. Posts are ordered by their published date (the third line in a post's file) in descending order. It means that in the default template the posts are aligned from left to right and then top to bottom, i.e. diagonally from top left to bottom right.
2. There's no support for pagination. Also, please note that **I don't plan to add more features** as already stated in issue #1.
