### ISSUE TITLE
How can I have LitePub ignore dot files?

### ISSUE THREAD

**Issue by phayz** [mirovarga/litepub#8]
I have started afresh with trying to host LitePub on GitLab. All is going well until GitLab's CI attempts a build. LitePub insists on having an empty `draft` sub-directory in the `posts` directory, so I created one. However as that is an empty directory, and git doesn't manage empty directories, GitLab created a `.gitkeep` file in the `draft` directory.

On attempting a build, LitePub fails with the following message:

~~~
ERROR: Failed to generate blog: Failed to read posts: Title, date or content is missing: posts/draft/.gitkeep
~~~

**Comment by mirovarga** [comment]
I just added a fix to ignore post files starting with a dot - please update to the [latest release](https://github.com/mirovarga/litepub/releases/tag/0.5.3).
